// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class ClaimHistory
    {
        public Guid Id { get; set; }
        public Guid? ClaimId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Guid? JobsId { get; set; }
        public string ImagePath { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual Claim Claim { get; set; }
        public virtual User CreatedByNavigation { get; set; }
        public virtual Job Jobs { get; set; }
    }
}