// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class ClaimType
    {
        public ClaimType()
        {
            Claims = new HashSet<Claim>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Claim> Claims { get; set; }
    }
}