// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class Engineer
    {
        public Engineer()
        {
            Claims = new HashSet<Claim>();
        }

        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Other { get; set; }
        public string Mobile { get; set; }
        public string Cvpath { get; set; }
        public string HomeAddress { get; set; }
        public string CompanyAddress { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Email { get; set; }
        public string MobileUserName { get; set; }
        public decimal Payrate { get; set; }
        public bool? WorkOnMonday { get; set; }
        public bool? WorkOnTuesday { get; set; }
        public bool? WorkOnWednesday { get; set; }
        public bool? WorkOnThursday { get; set; }
        public bool? WorkOnFriday { get; set; }
        public bool WorkOnSaturday { get; set; }
        public bool WorkOnSunday { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public long? CreatedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public string Office { get; set; }
        public string Home { get; set; }
        public string LandLine { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string GasSafeNumber { get; set; }
        public DateTime? GasSafeExpiry { get; set; }
        public string PublicLiabilityDocumentInsurance { get; set; }
        public DateTime? PublicLiabilityDocumentInsuranceExpiry { get; set; }
        public long? UserId { get; set; }
        public Guid? TypeId { get; set; }
        public bool? Work24Hr { get; set; }
        public bool? IsActive { get; set; }
        public string PictureUrl { get; set; }
        public string SpecialNotes { get; set; }
        public bool? PrefferredForService { get; set; }
        public bool? SelfAssignEngineer { get; set; }
        public decimal? Rating { get; set; }
        public bool? IsVatRegistered { get; set; }
        public string VatNumber { get; set; }
        public string CompanyLogo { get; set; }
        public string Abbr { get; set; }
        public string Logo { get; set; }
        public string AppointmentColour { get; set; }
        public string GasSafeLicenseNumber { get; set; }
        public string EngSigImg { get; set; }
        public string EngCertName { get; set; }
        public int? Monday { get; set; }
        public int? Tuesday { get; set; }
        public int? Wednesday { get; set; }
        public int? Thursday { get; set; }
        public int? Friday { get; set; }
        public int? Saturday { get; set; }
        public int? Sunday { get; set; }
        public DateTime? Dob { get; set; }
        public string PersonalAddressEp { get; set; }
        public string PersonalPhoneEp { get; set; }
        public string PersonalEmailEp { get; set; }
        public string WorkPhoneEp { get; set; }
        public string WorkEmailEp { get; set; }
        public DateTime? StartDateEp { get; set; }
        public string GasEngineerNumberEp { get; set; }
        public string MobileNameEp { get; set; }
        public string IbnnumberEp { get; set; }
        public long? EngStatusId { get; set; }
        public long? CarId { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public Guid? GroupId { get; set; }
        public string Epostcode { get; set; }
        public DateTime? CarAssignDateTime { get; set; }
        public string TrackerImei { get; set; }
        public string TrackerSimNumber { get; set; }
        public string SimProvider { get; set; }
        public string MobileAppVersion { get; set; }
        public bool? InstallEngineer { get; set; }
        public bool? SubContractor { get; set; }
        public string VanSize { get; set; }
        public long? VanStockBid { get; set; }
        public DateTime? VanStockDate { get; set; }
        public string VanReStockDay { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
    }
}