// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class Job
    {
        public Job()
        {
            ClaimHistories = new HashSet<ClaimHistory>();
        }

        public Guid Id { get; set; }
        public Guid ClaimId { get; set; }
        public Guid EngineerId { get; set; }
        public long JobId { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool IsComplete { get; set; }
        public DateTime BookingDate { get; set; }
        public string BookingAddress { get; set; }
        public string AllocatedEngineerTime { get; set; }
        public DateTime EngineerAllocatedForDate { get; set; }
        public DateTime? EndServiceDate { get; set; }
        public string JobType { get; set; }
        public string TicketEmail { get; set; }
        public string AppointmentTime { get; set; }
        public decimal? Estimatesfnol { get; set; }
        public string Estimatesfnoldescription { get; set; }
        public decimal? Parts { get; set; }
        public string Partsfnoldescription { get; set; }
        public decimal? Labour { get; set; }
        public string Labourdescription { get; set; }
        public decimal? Other { get; set; }
        public string Otherdescription { get; set; }
        public decimal? Agreedamount { get; set; }
        public string Agreedamountdescription { get; set; }
        public decimal? Grandtotal { get; set; }
        public decimal? NetAmount { get; set; }
        public decimal? VatAmount { get; set; }
        public decimal? GrossAmount { get; set; }
        public decimal? EngineerEstimatesfnol { get; set; }
        public string EngineerEstimatesfnoldescription { get; set; }
        public decimal? EngineerParts { get; set; }
        public string EngineerPartsfnoldescription { get; set; }
        public decimal? EngineerLabour { get; set; }
        public string EngineerLabourdescription { get; set; }
        public decimal? EngineerOther { get; set; }
        public string EngineerOtherdescription { get; set; }
        public decimal? EngineerAgreedamount { get; set; }
        public string EngineerAgreedamountdescription { get; set; }
        public decimal? EngineerGrandtotal { get; set; }
        public bool InvoiceCreated { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public decimal? EngineerNet { get; set; }
        public decimal? EngineerVat { get; set; }
        public decimal? EngineerGross { get; set; }
        public bool? InvoiceApproved { get; set; }
        public long? InvoiceApprovedBy { get; set; }
        public DateTime? InvoiceApprovedDate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Age { get; set; }
        public string Notes { get; set; }
        public string AppointmentEndTime { get; set; }
        public bool? JobCompleted { get; set; }
        public decimal? Rating { get; set; }
        public string Ratenote { get; set; }
        public string Filepath { get; set; }
        public bool? CannotGetContactToGetAccess { get; set; }
        public bool? AppointmentBooked { get; set; }
        public string JobStatus { get; set; }
        public int? EngineerClusterAppointmentId { get; set; }
        public string RiskContactName { get; set; }
        public string RiskContactNo1 { get; set; }
        public string RiskContactNo2 { get; set; }
        public string EngineerReportParts { get; set; }
        public string MoreInfo { get; set; }
        public int? RouteOrder { get; set; }
        public decimal? Distance { get; set; }
        public long? RequiredArrTime { get; set; }
        public string ApproxArrTime { get; set; }
        public string TimeType { get; set; }
        public decimal? DistanceBetweenJobs { get; set; }
        public string TimeBetweenJobs { get; set; }
        public string DetailsWork { get; set; }
        public int? NoOfAppTested { get; set; }
        public DateTime? NextDueDt { get; set; }
        public string Ogins { get; set; }
        public string Ogsup { get; set; }
        public string Econ { get; set; }
        public string Ogtight { get; set; }
        public string EquiBond { get; set; }
        public string SigImage { get; set; }
        public string SigRec { get; set; }
        public DateTime? FlueChkDt { get; set; }
        public string CertificateName { get; set; }
        public DateTime? CertificateDate { get; set; }
        public DateTime? ArrivedAtJobDatetime { get; set; }
        public decimal? Points { get; set; }
        public bool? ShowJobsOnEapp { get; set; }
        public int? AuthMreason { get; set; }
        public string AuthMmake { get; set; }
        public string AuthMmodel { get; set; }
        public int? AuthMage { get; set; }
        public decimal? AuthMboilerValue { get; set; }
        public decimal? AuthMmarketValue { get; set; }
        public decimal? AuthMberlimit { get; set; }
        public decimal? AuthCostOfLabour { get; set; }
        public string AuthTotalCntrbtnPartsCostFormula { get; set; }
        public string AuthBerlimitTotalCntrbtnFormula { get; set; }
        public string AuthTotalCntrbtnFormula { get; set; }
        public string AuthCntrbtnToCollectFormula { get; set; }
        public decimal? Auth1stHour { get; set; }
        public decimal? AuthAdditionalHour { get; set; }
        public bool? AuthMissedDiagnosis { get; set; }
        public int? AuthBerReasonId { get; set; }
        public int? AuthOutcomeId { get; set; }
        public string AuthGivenHour { get; set; }
        public string AuthGivenMin { get; set; }
        public DateTime? AuthGivenDateTime { get; set; }
        public long? AuthGivenBy { get; set; }
        public DateTime? OnRoute { get; set; }
        public DateTime? ArrivedAtJob { get; set; }
        public DateTime? EngineerJobCompleteDate { get; set; }
        public Guid? FkJsid { get; set; }
        public bool? NewInvoiceRoutine { get; set; }
        public int? NewRouteOrder { get; set; }
        public decimal? NewDistance { get; set; }
        public string NewEstimatedArrTime { get; set; }
        public string NewActualArrTime { get; set; }
        public decimal? NewDistanceBetweenJobs { get; set; }
        public decimal? NewTimeBetweenJobs { get; set; }
        public string SigImageBase64 { get; set; }
        public bool? IsAllPartsConfirmed { get; set; }
        public long? PartsConfirmedBy { get; set; }
        public DateTime? PartsConfirmedOn { get; set; }
        public string Cofitted { get; set; }
        public string Cotested { get; set; }
        public int? ComboClaimJobId { get; set; }
        public bool? ComboIsComplete { get; set; }
        public string ComboCantCompleteReason { get; set; }

        public virtual Claim Claim { get; set; }
        public virtual ICollection<ClaimHistory> ClaimHistories { get; set; }
    }
}