// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class Product
    {
        public Product()
        {
            Claims = new HashSet<Claim>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public int? TypeOfClaim247 { get; set; }
        public bool? DoNotSmsnextDay { get; set; }
        public bool? IsClaim { get; set; }
        public int? DisplayOrder { get; set; }
        public int? FkProductTypeId { get; set; }
        public string NominalCode { get; set; }
        public int Numberid { get; set; }
        public bool? IsActualService { get; set; }
        public int? WeekendPoints { get; set; }
        public int? WeekdayPoints { get; set; }
        public int? Crm247productId { get; set; }
        public string IconUpload { get; set; }
        public int? AcceptedFrom { get; set; }
        public int? AcceptedTo { get; set; }
        public int? ReferredFrom { get; set; }
        public int? ReferredTo { get; set; }
        public int? DeclinedFrom { get; set; }
        public int? DeclinedTo { get; set; }
        public bool? Underwriting { get; set; }
        public decimal? Auth1stHour { get; set; }
        public decimal? AuthAdditionalHours { get; set; }
        public decimal? AuthMissedDiagnosis { get; set; }
        public bool? OnDemandEta { get; set; }
        public bool? SiteSurveyCheck { get; set; }
        public decimal? HourlyRate { get; set; }
        public string InvoiceNumberAbrv { get; set; }
        public bool? IsFreshClaim { get; set; }
        public bool? IsGasClaim { get; set; }
        public bool? IsWaterClaim { get; set; }
        public bool? IsHeclaim { get; set; }
        public bool? IsServiceClaim { get; set; }
        public bool? IsCp12claim { get; set; }

        public virtual ICollection<Claim> Claims { get; set; }
    }
}