// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class SiteSurveyImage
    {
        public Guid ImgId { get; set; }
        public Guid? Ssid { get; set; }
        public string ImageName { get; set; }
    }
}