// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class SiteSurveyNew
    {
        public SiteSurveyNew()
        {
            SiteSurveyPhotos = new HashSet<SiteSurveyPhoto>();
        }

        public Guid Id { get; set; }
        public Guid? ClaimId { get; set; }
        public string NoOfRadiators { get; set; }
        public string NoOfShowers { get; set; }
        public string AnyAsbestos { get; set; }
        public string AsbestosNotes { get; set; }
        public string EquipotentialBondingGas { get; set; }
        public string LocateStopWater { get; set; }
        public string WaterStopTested { get; set; }
        public string ElectricBoardLocation { get; set; }
        public string EarthLoopTest { get; set; }
        public string BoilerType { get; set; }
        public string BoilerMake { get; set; }
        public string BoilerModel { get; set; }
        public string BoilerLocation { get; set; }
        public string BuildingWorkAfterRemoval { get; set; }
        public string HeatingSystemType { get; set; }
        public string HeatingSysTypeDescribe { get; set; }
        public string FlushRequired { get; set; }
        public string ChkRadiatorValves { get; set; }
        public string WaterPressure { get; set; }
        public decimal? GasTigthnessTest { get; set; }
        public string WorkInletPressure { get; set; }
        public string WorkInletPressureNote { get; set; }
        public string MeterWorkingPressure { get; set; }
        public string MeterWorkingPressureNote { get; set; }
        public string TypeOfFlush { get; set; }
        public string PboierSameLocation { get; set; }
        public string ConversionType { get; set; }
        public string PboilerLocation { get; set; }
        public string PboilerMake { get; set; }
        public string PboilerFlueType { get; set; }
        public string StandOffKitReq { get; set; }
        public string NewSystemUnvented { get; set; }
        public string FilterRequired { get; set; }
        public string LimescaleReducer { get; set; }
        public string PcondenseTermination { get; set; }
        public string ScaffoldingReq { get; set; }
        public decimal? FlueExtensions { get; set; }
        public decimal? FlueClamps { get; set; }
        public decimal? DegreeElbow45 { get; set; }
        public decimal? DegreeElbow90 { get; set; }
        public decimal? NoOfDays { get; set; }
        public string NoOfEngineers { get; set; }
        public string Trvreq { get; set; }
        public string NoOfTrv { get; set; }
        public string LockShieldsReq { get; set; }
        public string ExistingGasBeUsed { get; set; }
        public string ExistingGasLength { get; set; }
        public string FloringBeRemoved { get; set; }
        public string FurnitureBeMoved { get; set; }
        public string MountedPipeworkPosition { get; set; }
        public string CylinderRemoved { get; set; }
        public string NoOfLockShield { get; set; }
        public string BrequireFuseSpur { get; set; }
        public string DrainOffPoint { get; set; }
        public string DrainOffPointNote { get; set; }
        public string CustomerInstructions { get; set; }
        public string AdditionalNotes { get; set; }
        public bool TermsAndConditions { get; set; }
        public string SignedSurveyor { get; set; }
        public string SurveyorPrintName { get; set; }
        public string SignedCustomer { get; set; }
        public string CustomerPrintName { get; set; }
        public string CylinderRequired { get; set; }
        public string ExternalPumpRequired { get; set; }
        public string TwoPortValvesRequired { get; set; }
        public string ThreePortValve { get; set; }
        public string SurveyorSignatureImageName { get; set; }
        public string CustomerSignatureImageName { get; set; }
        public string GasRun { get; set; }
        public string NboilerLocation { get; set; }
        public string NboilerDesc { get; set; }
        public string NgasRun { get; set; }
        public string Ncondensate { get; set; }
        public int? NflueExtensions { get; set; }
        public int? NdegreeElbow45 { get; set; }
        public int? NdegreeElbow90 { get; set; }
        public bool? Install { get; set; }
        public bool? InstallationCompleted { get; set; }
        public bool? NoDefects { get; set; }
        public bool? NoDamageDuringInstallation { get; set; }
        public string InstallationCompletedReason { get; set; }
        public string NoDefectsReason { get; set; }
        public string NoDamageDuringInstallationReason { get; set; }
        public string CertificatePath { get; set; }
        public DateTime? CreatedDate { get; set; }
        public decimal? StandingInletPressure { get; set; }
        public decimal? WorkingInletPressure { get; set; }
        public string SiteSurveyReason { get; set; }
        public string SiteSurveyProductType { get; set; }

        public virtual Claim Claim { get; set; }
        public virtual ICollection<SiteSurveyPhoto> SiteSurveyPhotos { get; set; }
    }
}