// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EngineersAppWebCore.Models
{
    public partial class User
    {
        public User()
        {
            ClaimHistories = new HashSet<ClaimHistory>();
            Engineers = new HashSet<Engineer>();
        }

        public long Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public Guid UserGuid { get; set; }
        public bool Deleted { get; set; }
        public DateTime? FirstLoginDate { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public long? CreatedBy { get; set; }
        public long? UpdatedBy { get; set; }
        public bool? SelfAssignEngineer { get; set; }
        public string TempPassword { get; set; }
        public int WrongPasswordAttempt { get; set; }
        public bool LoginLocked { get; set; }
        public bool ResetPasswordRequested { get; set; }
        public DateTime? TempPasswordCreatedOn { get; set; }
        public bool? IsAccountManager { get; set; }
        public DateTime? PasswordChangeDate { get; set; }
        public Guid? TeamId { get; set; }
        public bool? CanSeeComplaint { get; set; }
        public bool? CanMoveComplaint { get; set; }
        public bool? CanViewInvoice { get; set; }
        public string Token { get; set; }
        public bool? CanManageSubcontractorClusters { get; set; }

        public virtual ICollection<ClaimHistory> ClaimHistories { get; set; }
        public virtual ICollection<Engineer> Engineers { get; set; }
    }
}